"""Render reaction snapshot packages generated by the C++ core."""

from __future__ import annotations

import csv
import contextlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
from PIL import Image, ImageDraw, ImageFont


ATOM_COLORS = {
    "H": "#f5f5f5",
    "C": "#555555",
    "N": "#3050f8",
    "O": "#ff0d0d",
    "P": "#ff8000",
    "S": "#ffff30",
    "Fe": "#e06633",
}
ATOM_RADII = {
    "H": 0.22,
    "C": 0.34,
    "N": 0.34,
    "O": 0.34,
    "P": 0.42,
    "S": 0.42,
    "Fe": 0.46,
}
DEFAULT_ATOM_RADIUS = 0.30
PANEL_SIZE = (620, 560)
LABEL_HEIGHT = 120
MARGIN = 24
GAP = 16
ARROW_WIDTH = 260


@dataclass(frozen=True)
class RenderedPanel:
    image: Image.Image
    title: str


def _bond_pair(value: str) -> tuple[int, int]:
    a, b = value.split("-", 1)
    ia, ib = int(a), int(b)
    return (ia, ib) if ia < ib else (ib, ia)


def _bond_set(values: Iterable[str]) -> set[tuple[int, int]]:
    return {_bond_pair(value) for value in values}


def _molecule_items(snapshot: dict, side: str) -> list[dict]:
    key = "reactants" if side == "reactant" else "products"
    return list(snapshot.get(key, []))


def _coords_by_id(snapshot: dict, side: str) -> dict[int, dict]:
    key = "reactant_coords" if side == "reactant" else "product_coords"
    return {int(atom["id"]): atom for atom in snapshot.get(key, [])}


def _bonds_for_side(snapshot: dict, side: str) -> list[dict]:
    key = "reactant_bonds" if side == "reactant" else "product_bonds"
    return list(snapshot.get(key, []))


def _subset_panel_data(snapshot: dict, side: str, molecule: dict) -> tuple[list[dict], list[dict]]:
    atom_ids = {int(value) for value in molecule.get("atom_ids", [])}
    coords = _coords_by_id(snapshot, side)
    atoms = [coords[atom_id] for atom_id in sorted(atom_ids) if atom_id in coords]
    bonds = [
        bond
        for bond in _bonds_for_side(snapshot, side)
        if int(bond["a"]) in atom_ids and int(bond["b"]) in atom_ids
    ]
    return atoms, bonds


def _camera_scale(points: np.ndarray, margin: float = 1.75) -> float:
    if len(points) == 0:
        return 1.0
    span = np.ptp(points, axis=0)
    return max(2.4, 0.5 * float(max(span[0], span[1], span[2])) * margin)


@contextlib.contextmanager
def _suppress_native_stderr():
    """Temporarily silence C/C++ stderr noise emitted by VTK render windows."""
    try:
        stderr_fd = 2
        saved = os.dup(stderr_fd)
        with open(os.devnull, "w") as devnull:
            os.dup2(devnull.fileno(), stderr_fd)
            try:
                yield
            finally:
                os.dup2(saved, stderr_fd)
                os.close(saved)
    except Exception:
        yield


def _render_molecule_panel(
    atoms: list[dict],
    bonds: list[dict],
    *,
    title: str,
    changed_bonds: set[tuple[int, int]],
    change_color: str,
) -> RenderedPanel:
    with _suppress_native_stderr():
        return _render_molecule_panel_impl(
            atoms,
            bonds,
            title=title,
            changed_bonds=changed_bonds,
            change_color=change_color,
        )


def _render_molecule_panel_impl(
    atoms: list[dict],
    bonds: list[dict],
    *,
    title: str,
    changed_bonds: set[tuple[int, int]],
    change_color: str,
) -> RenderedPanel:
    import pyvista as pv

    coords = {int(atom["id"]): np.array([float(atom["x"]), float(atom["y"]), float(atom["z"])]) for atom in atoms}
    elements = {int(atom["id"]): str(atom["element"]) for atom in atoms}
    focus_atoms = {atom_id for bond in changed_bonds for atom_id in bond}

    pv.OFF_SCREEN = True
    plotter = pv.Plotter(off_screen=True, window_size=PANEL_SIZE)
    plotter.set_background("white")
    try:
        plotter.enable_anti_aliasing("fxaa")
    except Exception:
        pass

    arrow_targets: list[np.ndarray] = []
    for bond in bonds:
        a = int(bond["a"])
        b = int(bond["b"])
        if a not in coords or b not in coords:
            continue
        p0 = coords[a]
        p1 = coords[b]
        vec = p1 - p0
        length = float(np.linalg.norm(vec))
        if length <= 1e-8:
            continue
        pair = (a, b) if a < b else (b, a)
        is_changed = pair in changed_bonds
        cyl = pv.Cylinder(
            center=(p0 + p1) / 2,
            direction=vec,
            radius=0.052,
            height=length,
            resolution=20,
        )
        plotter.add_mesh(cyl, color="#b8b8b8", smooth_shading=True)
        if is_changed:
            arrow_targets.append((p0 + p1) / 2)

    for atom_id, xyz in coords.items():
        elem = elements[atom_id]
        focused = atom_id in focus_atoms
        sphere = pv.Sphere(
            radius=ATOM_RADII.get(elem, DEFAULT_ATOM_RADIUS) * (1.25 if focused else 1.0),
            center=xyz,
            theta_resolution=32,
            phi_resolution=32,
        )
        plotter.add_mesh(
            sphere,
            color=ATOM_COLORS.get(elem, "#aaaaaa"),
            smooth_shading=True,
            specular=0.35,
            specular_power=24,
        )

    all_points = np.vstack(list(coords.values())) if coords else np.zeros((1, 3))
    center = all_points.mean(axis=0)
    extent = np.ptp(all_points, axis=0)
    span = max(7.0, float(np.linalg.norm(extent)) * 3.3)
    arrow_offset = np.array([0.0, 0.0, max(1.2, float(max(extent)) * 0.28)])
    for target in arrow_targets:
        arrow = pv.Arrow(
            start=target + arrow_offset,
            direction=-arrow_offset,
            scale=max(0.9, float(np.linalg.norm(arrow_offset)) * 0.82),
            tip_length=0.35,
            tip_radius=0.12,
            shaft_radius=0.035,
        )
        plotter.add_mesh(arrow, color=change_color, smooth_shading=True)

    plotter.camera_position = (
        tuple(center + np.array([span, -span, span * 0.85])),
        tuple(center),
        (0.0, 0.0, 1.0),
    )
    plotter.camera.parallel_projection = True
    extra_points = np.vstack(arrow_targets) if arrow_targets else center.reshape(1, 3)
    plotter.camera.parallel_scale = _camera_scale(np.vstack([all_points, extra_points]))
    plotter.add_light(pv.Light(position=tuple(center + np.array([span, -span, span])), focal_point=tuple(center), intensity=0.65))

    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        plotter.screenshot(tmp.name)
        panel = Image.open(tmp.name).convert("RGB")
    plotter.close()
    return RenderedPanel(image=panel, title=title)


def _font(size: int) -> ImageFont.ImageFont:
    for path in [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    ]:
        if Path(path).exists():
            return ImageFont.truetype(path, size=size)
    return ImageFont.load_default()


def _text_size(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.ImageFont) -> tuple[int, int]:
    box = draw.textbbox((0, 0), text, font=font)
    return box[2] - box[0], box[3] - box[1]


def _draw_centered_text(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], text: str, font: ImageFont.ImageFont, fill: str) -> None:
    lines = text.splitlines() or [text]
    sizes = [_text_size(draw, line, font) for line in lines]
    w = max((size[0] for size in sizes), default=0)
    h = sum(size[1] for size in sizes) + max(0, len(lines) - 1) * 6
    x0, y0, x1, y1 = box
    y = y0 + (y1 - y0 - h) / 2
    for line, (line_w, line_h) in zip(lines, sizes):
        draw.text((x0 + (x1 - x0 - line_w) / 2, y), line, font=font, fill=fill)
        y += line_h + 6


def _arrow_panel(height: int, text: str) -> Image.Image:
    panel = Image.new("RGB", (ARROW_WIDTH, height), "white")
    draw = ImageDraw.Draw(panel)
    mid = height // 2
    line_y = mid + 22
    draw.line((18, line_y, ARROW_WIDTH - 24, line_y), fill="#444444", width=5)
    draw.polygon(
        [(ARROW_WIDTH - 24, line_y), (ARROW_WIDTH - 48, line_y - 15), (ARROW_WIDTH - 48, line_y + 15)],
        fill="#444444",
    )
    _draw_centered_text(draw, (10, mid - 72, ARROW_WIDTH - 10, mid + 8), text, _font(26), "#222222")
    return panel


def _annotate_panel(panel: RenderedPanel) -> Image.Image:
    out = Image.new("RGB", (PANEL_SIZE[0], PANEL_SIZE[1] + LABEL_HEIGHT), "white")
    out.paste(panel.image, (0, 0))
    draw = ImageDraw.Draw(out)
    draw.rectangle((0, PANEL_SIZE[1], PANEL_SIZE[0], PANEL_SIZE[1] + LABEL_HEIGHT), fill="#f7f7f7")
    _draw_centered_text(draw, (8, PANEL_SIZE[1] + 8, PANEL_SIZE[0] - 8, PANEL_SIZE[1] + LABEL_HEIGHT - 8), panel.title, _font(30), "#111111")
    draw.rectangle((0, 0, PANEL_SIZE[0] - 1, PANEL_SIZE[1] + LABEL_HEIGHT - 1), outline="#cccccc", width=1)
    return out


def _change_summary(atoms: list[dict], bonds: list[dict], changed_bonds: set[tuple[int, int]], label: str) -> str:
    if not changed_bonds:
        return ""
    elements = {int(atom["id"]): str(atom["element"]) for atom in atoms}
    parts: list[str] = []
    for bond in bonds:
        a = int(bond["a"])
        b = int(bond["b"])
        pair = (a, b) if a < b else (b, a)
        if pair not in changed_bonds:
            continue
        ai = elements.get(a, "")
        bi = elements.get(b, "")
        parts.append(f"{ai}-{bi} {float(bond['length']):.2f} A")
    if not parts:
        return ""
    return f"{label}: " + "; ".join(parts[:2])


def _safe_reaction_name(value: str) -> str:
    keep = []
    for char in value:
        if char.isalnum() or char in {"+", "-"}:
            keep.append(char)
        else:
            keep.append("_")
    return "".join(keep).strip("_") or "reaction"


def _snapshot_image_name(snapshot: dict) -> str:
    reactants = _safe_reaction_name(str(snapshot.get("reactant_formulas", "R")))
    products = _safe_reaction_name(str(snapshot.get("product_formulas", "P")))
    return f"reaction_{reactants}_{products}_{int(snapshot['event_id']):06d}.jpg"


def render_snapshot(snapshot_path: Path, output_dir: Path, *, force: bool = False) -> Path:
    snapshot = json.loads(snapshot_path.read_text())
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / _snapshot_image_name(snapshot)
    if out.exists() and not force:
        return out

    broken = _bond_set(snapshot.get("broken_bond_ids", []))
    created = _bond_set(snapshot.get("created_bond_ids", []))

    panels: list[Image.Image] = []
    for idx, mol in enumerate(_molecule_items(snapshot, "reactant"), start=1):
        atoms, bonds = _subset_panel_data(snapshot, "reactant", mol)
        title = f"Reactant {idx}: {mol.get('formula', '')}"
        summary = _change_summary(atoms, bonds, broken, "broken")
        if summary:
            title += f"\n{summary}"
        panels.append(_annotate_panel(_render_molecule_panel(atoms, bonds, title=title, changed_bonds=broken, change_color="#d62728")))

    time_text = f"frame\n{snapshot.get('reactant_frame')} -> {snapshot.get('product_frame')}"
    panels.append(_arrow_panel(PANEL_SIZE[1] + LABEL_HEIGHT, time_text))

    for idx, mol in enumerate(_molecule_items(snapshot, "product"), start=1):
        atoms, bonds = _subset_panel_data(snapshot, "product", mol)
        title = f"Product {idx}: {mol.get('formula', '')}"
        summary = _change_summary(atoms, bonds, created, "created")
        if summary:
            title += f"\n{summary}"
        panels.append(_annotate_panel(_render_molecule_panel(atoms, bonds, title=title, changed_bonds=created, change_color="#2ca02c")))

    width = MARGIN * 2 + sum(panel.width for panel in panels) + GAP * (len(panels) - 1)
    height = MARGIN * 2 + max(panel.height for panel in panels)
    montage = Image.new("RGB", (width, height), "white")
    x = MARGIN
    y = MARGIN
    for panel in panels:
        montage.paste(panel, (x, y + (height - 2 * MARGIN - panel.height) // 2))
        x += panel.width + GAP

    montage.save(out, quality=95)
    return out


def render_snapshot_directory(root: Path, *, limit: int | None = 30, force: bool = False) -> list[Path]:
    snapshot_dir = root / "reaction_snapshots"
    if not snapshot_dir.exists():
        raise FileNotFoundError(f"Missing reaction snapshot directory: {snapshot_dir}")
    manifest = snapshot_dir / "snapshots_manifest.csv"
    if not manifest.exists():
        raise FileNotFoundError(f"Missing snapshot manifest: {manifest}")

    rows = list(csv.DictReader(manifest.open(newline="")))
    written: list[Path] = []
    image_dir = snapshot_dir / "montage"
    selected = rows if limit is None else rows[:limit]
    for row in selected:
        path = snapshot_dir / row["path"]
        if not path.exists():
            continue
        written.append(render_snapshot(path, image_dir, force=force))
    return written
