name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy-pages-v1.98  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web'    # 你的 HTML 文件在 web 文件夹下
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4